services:
  vt-scanner:
    image: vt-scanner:latest
    build: .
    container_name: vt-scanner
    restart: unless-stopped
    init: true
    env_file:
      - .env
    networks:
      - xai

networks:
  xai:
    external: true
